### ISSUE TITLE
Minified js

### ISSUE THREAD

**Issue by HadrienWonderwalls** [pegasus1982/threejs-3d-room-designer#3]
Hi Pegasus, 

Great work. 
You only share the minified version of the code for this repository. Is there anyway you could share the non-minified version of the code? 

Sincerely, 

Hadrien

**Comment by pegasus1982** [comment]
Hi @HadrienWonderwalls 
As I signed on NDA, I can't publish source code now.
If you are still interesting, please leave your email.
Thank your for your interest.

**Comment by pegasus1982** [comment]
@HadrienWonderwalls 
I've sent email.

**Comment by mcesar29** [comment]
Hey @pegasus1982 can we talk by email? my email is michael_cesar_sv@hotmail.com

**Comment by pegasus1982** [comment]
@mcesar29 
I've sent email.

**Comment by adaniello** [comment]
@pegasus1982 I too, thank you achille.daniello@gmail.com

**Comment by pegasus1982** [comment]
@adaniello 
I've sent email

**Comment by adaniello** [comment]
> @adaniello I've sent email

Thank you

**Comment by Nutlope** [comment]
Also interested @pegasus1982. Can you reach out to hassan@hey.com please?

**Comment by pegasus1982** [comment]
@Nutlope 
I've sent email

**Comment by yaghdev** [comment]
Great work @pegasus1982. I am also interested, can you please reach out at yaghdevpaliwal@gmail.com

**Comment by bilgehanm** [comment]
Impressive work @pegasus1982 , I am also interested, can you reach out at bilgehanm@gmail.com. Thanks

**Comment by jclaan** [comment]
also interested to chat - jason@laan.com

**Comment by bosombaby** [comment]
@pegasus1982 I am also interested, can you please reach out at1245924849@qq.com

**Comment by iznalfiden** [comment]
@pegasus1982 I'm also interested, thank you. My email - madiyar.iznalfiden@gmail.com 
(sorry for creating a separate question on this topic)

**Comment by ls153405636** [comment]
@pegasus1982 I am also interested, can you please reach out at153405636@qq.com,thanks!

**Comment by 5267lq** [comment]
I need it too.Thanks for your help! And my email - boxingliuqi@163.com

**Comment by 5267lq** [comment]
I am also interested. Thanks for your help! And my email - boxingliuqi@163.com @pegasus1982

**Comment by YenseanHub** [comment]
I am also quite interested,Thanks for your help! And my email - [yensean@foxmail.com](yensean@foxmail.com)@pegasus1982. Hope hear from U soon.

**Comment by adaniello** [comment]
@pegasus1982 Am I the only one who didn't receive anything? Thanks

**Comment by webfxd** [comment]
@pegasus1982 I am also interested, can you please reach out [fxdwytxz@gmail.com](mailto:fxdwytxz@gmail.com),Thank you!

**Comment by ersntrzi** [comment]
Hello, we are designing a room using the blueprint3d js library you use. There are 2 issues that we couldn't manage to do in our project. 

1. When we switch to 2D, we want to see the products from a bird's eye view and see the distances between them like you do.
2. When we move to 3D view, we want to measure the distance between the other objects, walls and etc. 

We need your help regarding these issues. You can reach me at caner@forivia.com or let us know the most convenient way for you to get in touch. We are interested in the source code as well. Please also let me know about the conditions of the NDA you've signed. 

Thanks in advance

**Comment by 2much2want** [comment]
Hi @pegasus1982 also interested, email is shebashepherd15@gmail.com

**Comment by Alex4242171** [comment]
Hello, nice work !
I'm also interested, email : alex.millet.171@gmail.com

**Comment by DonJayJay** [comment]
Hi @pegasus1982 also interested in the source, my email is jjcv10@gmail.com

**Comment by SergeyMelnyk** [comment]
@pegasus1982 
Hello! greate project, I am just started to learn three js, your project impres me, will be very appreciate for source melnykserhiy1@gmail.com

**Comment by leochen01** [comment]
@pegasus1982 I am also interested, can you please reach out [rainleaf@live.cn](mailto:rainleaf@live.cn),Thank you!

**Comment by MarcinTroska** [comment]
@pegasus1982 nice work, I would be interested in the source, can you reach out to me troska50@wp.pl - thanks

**Comment by awaisali88** [comment]
@pegasus1982 great work you have done there, 
I am interested in having the source code.
Can you reach out to me, my email is awais1988@live.com.

Thank you

**Comment by Th4p4** [comment]
Impressive work @pegasus1982 , I am also interested, can you reach out at [humanityisoverrated997@gmail.com](mailto:humanityisoverrated997@gmail.com). Thanks

**Comment by midhun4uhli** [comment]
@pegasus1982 it was really lovely.
 I am interested this application. Can you reach out to me, my email is Happylifeinteriors@gmail.com 

Basically am look for this kind of application for my small furniture business.
if you can help me out it will be great for us 

Thanks & Regards
Midhun

**Comment by pegasus1982** [comment]
Hell everyone
Current version is react-bundled one, please contact me via telegram (@pegasus_0000)

**Comment by tayyab-tariq** [comment]
Hi @pegasus1982, 
I am interested in the source code and would be extremely grateful if you could reach out to me at [jok3r4707@gmail.com](url) 
Thanks in advance.

PS: Telegram is blocked in my country which is why I can't send you a message.

**Comment by mahmoudaboelmagde** [comment]
Impressive work @pegasus1982 ,I am also interested, can you reach out at (mahmoudaly19970@gmail.com) , Thanks

**Comment by zx69** [comment]
Hi @pegasus1982, the project looks very grateful, can you reach out at ([zx611411281@gmail.com
](mailto:zx611411281@gmail.com)) , Thank you very much.

**Comment by Lutidza** [comment]
@pegasus1982 I am also interested, can you please reach out pacifica.pro@gmail.com
Thank you very much.
